services:

  database:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
      - ./docker-compose/init:/docker-entrypoint-initdb.d
    networks:
      - minecraft

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatfilter
    ports:
      - "5432:5432"
    volumes:
      - ./docker-compose/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 500
    networks:
      - minecraft

  cache:
    image: redis
    restart: no
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - ./docker-compose/redis:/data
    networks:
      - minecraft

  paper:
    image: itzg/minecraft-server
    restart: no
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: "1.20.2"
    depends_on:
      - database
      - cache
      - postgres
    volumes:
      - ./docker-compose/paper:/data
    networks:
      - minecraft

  proxy:
    image: itzg/mc-proxy
    restart: no
    environment:
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: Powered by Docker
      REPLACE_ENV_VARIABLES: "true"
    depends_on:
      - database
      - cache
      - postgres
    ports:
      - "25578:25577"
    volumes:
      - ./docker-compose/proxy/config.yml:/config/config.yml
      - ./docker-compose/proxy/server:/server
    networks:
      - minecraft

networks:
  minecraft:
