name: NetzChatFilter
version: '${project.version}'
main: de.netzkronehd.chatfilter.platform.spigot.ChatFilterSpigot
api-version: '1.13'
authors: [ NetzkroneHD ]
description: A chat filter plugin for Minecraft.

commands:
  netzchatfilter:
    description: Main command for the chat filter plugin.
    usage: /chatfilter <reload|parse|violations>
    permission: chatfilter.command
    aliases:
      - chatfilter
      - ncf
      - cf
