<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.netzkronehd.chatfilter</groupId>
        <artifactId>chatfilter</artifactId>
        <version>1.0.0</version>
    </parent>

    <properties>
        <kyori-bungeecord.version>4.3.4</kyori-bungeecord.version>
    </properties>

    <artifactId>chatfilter-bungee</artifactId>

    <repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.md-5</groupId>
            <artifactId>bungeecord-api</artifactId>
            <version>1.21-R0.4</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>de.netzkronehd.chatfilter</groupId>
            <artifactId>chatfilter-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/net.kyori/adventure-platform-bungeecord -->
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-bungeecord</artifactId>
            <version>${kyori-bungeecord.version}</version>
        </dependency>

        <!-- https://jitpack.io/#NetzkroneHD/Translation -->
        <dependency>
            <groupId>com.github.NetzkroneHD.Translation</groupId>
            <artifactId>translation-bungee</artifactId>
            <version>${translation.version}</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>NetzChatFilter-bungee-${project.version}</finalName>
        <defaultGoal>clean package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>
